common: vendor/init: Move early/post_boot scripts from soong
* Since legacy variants are copied out to the same place
  it causes 2 install targets for the respective install
  path, thus causing the following error:
  error: overriding commands for target `out/vendor/bin/init.qcom.post_boot.sh'

Change-Id: I246da97954566de2c07393eb320df7d96297b280
Signed-off-by: electimon <electimon@gmail.com>